version: "3"

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - SECRET_KEY=${SECRET_KEY}
      - DJANGO_ALLOWED_HOSTS=${DJANGO_ALLOWED_HOSTS}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_STORAGE_BUCKET_NAME=${AWS_STORAGE_BUCKET_NAME}
      - AWS_DEFAULT_ACL=${AWS_DEFAULT_ACL}
    depends_on:
      - db
    networks:
      - app-network

  db:
    image: mariadb:latest
    hostname: db
    container_name: mariadb_dchs_new
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    command: --max_allowed_packet=128505856 --lower_case_table_names=1
    volumes:
      - mariadbdata:/var/lib/mysql
    networks:
      - app-network
    ports:
      - "3307:3306"
    expose:
      - "3307"

networks:
  app-network:
    driver: bridge

volumes:
  mariadbdata: